# Generated by Django 2.2.6 on 2019-10-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auction_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='base_price',
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
