# Generated by Django 2.2.6 on 2019-10-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20191031_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='base_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
