# Generated by Django 2.2.6 on 2019-11-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_product_time_starting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='time_starting',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='time_starting',
            new_name='start_time',
        ),
    ]
